/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#0d111a",
        "error-dim": "#d73357",
        "surface-container-high": "#1c1f28",
        "tertiary-dim": "#e2242a",
        "on-tertiary-fixed-variant": "#7a000b",
        "tertiary-container": "#f53335",
        "surface": "#07090e",
        "on-secondary-fixed": "#003851",
        "error-container": "#a70138",
        "on-error": "#490013",
        "on-background": "#e7e7f1",
        "tertiary": "#ff7168",
        "primary-dim": "#8a4cfc",
        "on-primary": "#3c0089",
        "on-surface": "#e7e7f1",
        "surface-container": "#11141d",
        "on-error-container": "#ffb2b9",
        "tertiary-fixed-dim": "#ff7b71",
        "surface-bright": "#282c36",
        "surface-container-highest": "#1b1f28",
        "primary": "#bd9dff",
        "on-secondary": "#00344c",
        "secondary-dim": "#19aeee",
        "outline-variant": "#454850",
        "secondary-fixed": "#a0d9ff",
        "secondary-fixed-dim": "#7bcdff",
        "on-tertiary-fixed": "#3a0002",
        "inverse-on-surface": "#53555d",
        "on-primary-fixed": "#000000",
        "tertiary-fixed": "#ff9289",
        "on-primary-fixed-variant": "#390083",
        "secondary-container": "#00658d",
        "surface-tint": "#bd9dff",
        "surface-variant": "#22262f",
        "outline": "#73757e",
        "surface-dim": "#07090e",
        "on-surface-variant": "#a9abb4",
        "on-primary-container": "#2e006c",
        "background": "#07090e",
        "on-secondary-fixed-variant": "#005679",
        "inverse-primary": "#742fe5",
        "surface-container-lowest": "#000000",
        "inverse-surface": "#faf9ff",
        "primary-fixed": "#b28cff",
        "secondary": "#36bcfd",
        "error": "#ff6e84",
        "on-tertiary-container": "#000000",
        "primary-container": "#b28cff",
        "on-secondary-container": "#f2f8ff",
        "on-tertiary": "#4a0004",
        "primary-fixed-dim": "#a67aff"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
