KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="${KAFKA_SASL_USERNAME}"
    password="${KAFKA_SASL_PASSWORD}"
    user_sentinel="${KAFKA_SASL_PASSWORD}";
};

KafkaClient {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="${KAFKA_SASL_USERNAME}"
    password="${KAFKA_SASL_PASSWORD}";
};
