apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "10s"
      httpMethod: POST

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "sentinel-findings"
    isDefault: false
    editable: false
    jsonData:
      esVersion: "8.0.0"
      timeField: "indexed_at"
      interval: "Daily"
      logMessageField: "description"
      logLevelField: "severity"
